export type DeviceProperty = {
  id: string;
  type: string;
  displayName: string;
  isOn: boolean | undefined | null;
  temperatureInDegree: number | undefined | null;
  relativeHumidityInPercent: number | undefined | null;
  lux: number | undefined | null;
  batteryLevelInPercent: number | undefined | null;
  motionDetected: boolean | undefined | null;
  lastUpdated: Date | undefined | null;
  lastMotion: Date | undefined | null;
  watt: number | undefined | null;
  pressureInMillibar: number | undefined | null;
  isOpen: boolean | undefined | null;
  state: string | undefined | null;
  stateLastUpdated: Date | undefined | null;
  isOpenLastUpdated: Date | undefined | null;
  tiltAngleInDegree: number | undefined | null;
  tiltLastUpdated: Date | undefined | null;
  positionInPercent: number | undefined | null;
  positionLastUpdated: Date | undefined | null;
  dimmingLevelInPercent: number | undefined | null;
  ppm: number | undefined | null;
  uvIndex: number | undefined | null;
  isSmokeDetected: boolean | undefined | null;
  cloudBaseInMeter: number | undefined | null;
  rateInMmph: number | undefined | null;
  intervalMm: number | undefined | null;
  todayInMm: number | undefined | null;
  rateInMmphLastUpdated: Date | undefined | null;
  intervalMmLastUpdated: Date | undefined | null;
  todayInMmLastUpdated: Date | undefined | null;
  speedInKmh: number | undefined | null;
  gustSpeedInKmh: number | undefined | null;
  directionInDegree: number | undefined | null;
  gustDirectionInDegree: number | undefined | null;
  intervalRunInKm: number | undefined | null;
  speedLastUpdated: Date | undefined | null;
  gustSpeedLastUpdated: Date | undefined | null;
  directionLastUpdated: Date | undefined | null;
  gustDirectionLastUpdated: Date | undefined | null;
  intervalRunLastUpdated: Date | undefined | null;
}
